// Mirrors flock_os/tests/test_shard_parity.py golden values so the pure-JS
// crc32 in load/lib/shards.js stays byte-identical to Python's zlib.crc32
// (the shard-assignment parity contract, flock_os/realtime.py -> shard_for).
//
//   node --test load/lib/shards.test.mjs
import { test } from "node:test";
import assert from "node:assert/strict";
import { crc32, shardFor, shardChannel, broadcastChannel } from "./shards.js";

// [input, zlib.crc32 >>> 0, shard @ N=10]  (generated by Python zlib.crc32)
const GOLDEN = [
	["", 0, 0],
	["a", 3904355907, 7],
	["abc", 891568578, 8],
	["member-1", 2325991474, 4],
	["branch-a-member-0-0-0", 852893231, 1],
	["gathering-smoke-attendee-1", 84887220, 0],
	["x", 2363233923, 3],
	["Flock OS 15k smoke", 3096190035, 5],
];

test("crc32 matches Python zlib.crc32 for golden inputs", () => {
	for (const [input, expected] of GOLDEN) {
		assert.equal(crc32(input), expected, `crc32(${JSON.stringify(input)})`);
	}
});

test("shardFor matches the Python (crc32 % 10) assignment", () => {
	for (const [input, , shard] of GOLDEN) {
		assert.equal(shardFor(input, 10), shard, `shardFor(${JSON.stringify(input)})`);
	}
});

test("channel names match flock_os.realtime (flock_os:event:<id>:...)", () => {
	assert.equal(shardChannel("g1", 3), "flock_os:event:g1:shard:3");
	assert.equal(broadcastChannel("g1"), "flock_os:event:g1:broadcast");
});
