"""
Realtime shard-assignment parity lock (FLO-10 §5.1 / FLO-49).

The shard a client must join is ``crc32(utf8(attendee_ref)) >>> 0) % N`` — a
**cross-language contract**. The browser/k6 client (``load/lib/shards.js``)
must compute the *same* shard as the Python projector
(:func:`flock_os.realtime.shard_for`) or it joins the wrong room and misses
fan-out. Python's builtin ``hash()`` is per-process salted and cannot be used,
so both sides standardize on ``zlib.crc32``.

These golden values are mirrored verbatim in ``load/lib/shards.test.mjs`` so
``node --test`` keeps the JS port byte-identical to Python without a running
bench. Editing this table invalidates both sides — update them together.

Runs under plain ``pytest`` (no bench).
"""

from __future__ import annotations

import zlib

import pytest

from flock_os.realtime import (
	BROADCAST_SEGMENT,
	EVENT_ROOM_PREFIX,
	SHARD_SEGMENT,
	broadcast_channel,
	shard_channel,
	shard_for,
	shards_for,
)

# [attendee_ref, zlib.crc32 >>> 0, shard @ N=10]. Generated by zlib.crc32.
# Must stay identical to load/lib/shards.test.mjs GOLDEN.
_GOLDEN: list[tuple[str, int, int]] = [
	("", 0, 0),
	("a", 3904355907, 7),
	("abc", 891568578, 8),
	("member-1", 2325991474, 4),
	("branch-a-member-0-0-0", 852893231, 1),
	("gathering-smoke-attendee-1", 84887220, 0),
	("x", 2363233923, 3),
	("Flock OS 15k smoke", 3096190035, 5),
]


@pytest.mark.parametrize("ref, expected_crc, expected_shard", _GOLDEN)
def test_shard_for_matches_unsigned_crc32_mod_n(ref, expected_crc, expected_shard):
	# The cross-language contract: crc32 >>> 0 then mod N.
	assert (zlib.crc32(ref.encode()) & 0xFFFFFFFF) == expected_crc
	assert shard_for(ref) == expected_shard
	# Determinism: same ref → same shard across calls + custom shard counts.
	assert shard_for(ref) == shard_for(ref)
	for n in (2, 7, 10, 16):
		assert shard_for(ref, n) == expected_crc % n


def test_shards_for_is_sorted_deduped_subset():
	refs = [ref for ref, _, _ in _GOLDEN]
	result = shards_for(refs)
	assert result == sorted(set(result))
	assert set(result).issubset(set(range(10)))


def test_channel_names_match_the_parity_contract():
	# flock_os:event:<id>:shard:<n>  /  flock_os:event:<id>:broadcast
	assert shard_channel("g1", 3) == f"{EVENT_ROOM_PREFIX}:g1:{SHARD_SEGMENT}:3"
	assert broadcast_channel("g1") == f"{EVENT_ROOM_PREFIX}:g1:{BROADCAST_SEGMENT}"
