#!/usr/bin/env bash
#
# Flock OS backup/restore DRILL ([FLO-288](/FLO/issues/FLO-288) Phase 6.2).
#
# End-to-end restore-drill test against the local bench: backs the source site up,
# restores it into a fresh `flock_os_restore_drill` site, then asserts ROW-COUNT
# PARITY across every `Flock *` DocType present in the source. Exits non-zero on
# any mismatch — a green run is the Phase 6 acceptance proof "a restore drill
# succeeds from a real backup".
#
# App-version + VM independent: parity is checked with raw SQL via the mysql
# client (table counts), NOT the app/frappe, so it runs identically regardless of
# which DocTypes a release ships and on any bench (local or prod). The pure
# comparison logic lives in flock_os/utils/backup_drill.py (unit-covered).
#
# Idempotent across re-runs: restore.sh --force overwrites the drill site, so the
# drill is safe to run repeatedly.
#
# Usage:
#   scripts/dev/restore-drill.sh [options]
#     --source-site <name>   site to back up (default: $SITE_NAME / current site)
#     --drill-site <name>    restore target host (default: flock_os_restore_drill)
#     --bench-dir <path>     bench root (default: $BENCH_DIR)
#     --db-root-password <p> MariaDB root password (default: $MARIADB_ROOT_PASSWORD)
#     --db-root-username <u> MariaDB root user (default: $MARIADB_ROOT_USER / frappe_root;
#                            the docker-compose tier uses `root`)
#     --admin-password <p>   drill-site Administrator password (default: $SITE_ADMIN_PASSWORD)
#     --keep                 do NOT drop the drill site at the end (debug)
#     -h, --help
#
# Env (lower priority than flags; $REPO_ROOT/.env auto-loaded if present):
#   BENCH_DIR, SITE_NAME, MARIADB_ROOT_PASSWORD, MARIADB_ROOT_USER, SITE_ADMIN_PASSWORD
set -uo pipefail

PROG="$(basename "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

usage() { sed -n '3,/^$/p' "${BASH_SOURCE[0]}" >&2; }

load_env() {
	local env="$REPO_ROOT/.env"
	[[ -f "$env" ]] || return 0
	set -a
	# shellcheck disable=SC1090
	. "$env"
	set +a
}
load_env

# capture_counts <site> — print TSV "doctype<TAB>count" for every Flock % DocType
# in the site's DB, via raw SQL. Reads db_name/db_password from the site_config.
# App/version independent: discovers doctypes from tabDocType at runtime. Pure
# SQL is generated by the unit-covered flock_os.utils.backup_drill helpers.
# Stack-agnostic: the DB host is resolved from site_config.json (`host`) or the
# bench-level common_site_config.json (`db_host`), defaulting to 127.0.0.1 — so
# the SAME drill runs against the host bench (127.0.0.1) and the docker-compose
# topology (db_host=mariadb) without flag edits (FLO-353).
capture_counts() {
	local site="$1"
	local cfg="$BENCH_DIR/sites/$site/site_config.json"
	[[ -f "$cfg" ]] || return 1
	PYTHONPATH="$REPO_ROOT" python3 - "$cfg" <<'PY'
import json, os, subprocess, sys
from flock_os.utils.backup_drill import build_count_sql, build_doctype_discovery_sql

cfg = json.load(open(sys.argv[1]))
db, pw = cfg["db_name"], cfg["db_password"]


def resolve_db_host(site_cfg_path):
	# site_config.json `host` wins (per-site override); else the bench-level
	# common_site_config.json `db_host` (where the docker entrypoint writes it);
	# else the local-bench default. None -> 127.0.0.1 (host bench / mysql local).
	# common_site_config.json lives in the SITES dir (parent of the site dir),
	# i.e. sites/common_site_config.json — NOT sites/<site>/.
	host = cfg.get("host")
	if not host:
		sites_dir = os.path.dirname(os.path.dirname(site_cfg_path))
		csc = os.path.join(sites_dir, "common_site_config.json")
		if os.path.exists(csc):
			try:
				host = json.load(open(csc)).get("db_host")
			except Exception:
				host = None
	return host or "127.0.0.1"


host = resolve_db_host(sys.argv[1])


def run(sql):
	return subprocess.run(
		["mysql", "-h", host, "-u", db, f"-p{pw}", db, "-N", "-B", "-e", sql],
		capture_output=True, text=True,
	)


disc = run(build_doctype_discovery_sql())
if disc.returncode != 0:
	sys.stderr.write(disc.stderr)
	sys.exit(1)
doctypes = [line.strip() for line in disc.stdout.splitlines() if line.strip()]
sql = build_count_sql(doctypes)
if not sql:
	sys.exit(0)
cnt = run(sql)
if cnt.returncode != 0:
	sys.stderr.write(cnt.stderr)
	sys.exit(1)
sys.stdout.write(cnt.stdout)
PY
}

# drop_site <site> — best-effort drop (non-fatal). Needs root creds because the
# MariaDB site user cannot DROP its own database. Uses --force --no-backup (the
# drill site is throwaway) and pipes `yes` in case bench prompts for confirmation.
# The site dir is moved to archived/sites by bench, so re-check by dir presence.
drop_site() {
	local site="$1"
	[[ -d "$BENCH_DIR/sites/$site" ]] || return 0
	(cd "$BENCH_DIR" && yes \
		| command bench drop-site "$site" --force --no-backup \
			--db-root-username "$DB_ROOT_USER" --db-root-password "$DB_ROOT_PW" >/dev/null 2>&1) \
		|| (cd "$BENCH_DIR" && yes \
			| command bench drop-site "$site" --force --no-backup >/dev/null 2>&1) \
		|| true
	# bench drop-site archives the DB/files but can leave an `indexes/` stub dir;
	# remove any leftover so the site dir is fully gone.
	rm -rf "${BENCH_DIR:?}/sites/$site" 2>/dev/null || true
}

SOURCE_SITE="${SITE_NAME:-}"
DRILL_SITE="flock_os_restore_drill"
BENCH_DIR="${BENCH_DIR:-}"
DB_ROOT_PW="${MARIADB_ROOT_PASSWORD:-}"
DB_ROOT_USER="${MARIADB_ROOT_USER:-frappe_root}"
ADMIN_PW="${SITE_ADMIN_PASSWORD:-}"
KEEP=0

while [[ $# -gt 0 ]]; do
	case "$1" in
		--source-site) SOURCE_SITE="$2"; shift 2 ;;
		--source-site=*) SOURCE_SITE="${1#--source-site=}"; shift ;;
		--drill-site) DRILL_SITE="$2"; shift 2 ;;
		--drill-site=*) DRILL_SITE="${1#--drill-site=}"; shift ;;
		--bench-dir) BENCH_DIR="$2"; shift 2 ;;
		--bench-dir=*) BENCH_DIR="${1#--bench-dir=}"; shift ;;
		--db-root-password) DB_ROOT_PW="$2"; shift 2 ;;
		--db-root-password=*) DB_ROOT_PW="${1#--db-root-password=}"; shift ;;
		--db-root-username) DB_ROOT_USER="$2"; shift 2 ;;
		--db-root-username=*) DB_ROOT_USER="${1#--db-root-username=}"; shift ;;
		--admin-password) ADMIN_PW="$2"; shift 2 ;;
		--admin-password=*) ADMIN_PW="${1#--admin-password=}"; shift ;;
		--keep) KEEP=1; shift ;;
		-h|--help) usage; exit 0 ;;
		*) echo "$PROG: unknown arg: $1" >&2; exit 2 ;;
	esac
done

# --- resolve / validate -------------------------------------------------------
if [[ -z "$BENCH_DIR" ]]; then
	echo "$PROG: --bench-dir (or BENCH_DIR env) is required." >&2; exit 2
fi
[[ -d "$BENCH_DIR/sites" ]] || { echo "$PROG: $BENCH_DIR is not a bench (no sites/)." >&2; exit 2; }
[[ -n "$DB_ROOT_PW" ]] || { echo "$PROG: --db-root-password (or MARIADB_ROOT_PASSWORD) is required to create the drill site." >&2; exit 2; }
if [[ -z "$SOURCE_SITE" ]]; then
	cur="$BENCH_DIR/sites/currentsite.txt"
	[[ -f "$cur" && -s "$cur" ]] || { echo "$PROG: no --source-site and no current site." >&2; exit 2; }
	SOURCE_SITE="$(cat "$cur")"
fi
[[ -d "$BENCH_DIR/sites/$SOURCE_SITE" ]] || { echo "$PROG: source site $SOURCE_SITE not found." >&2; exit 2; }

DRILL_HOST="${DRILL_SITE}.localhost"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "Flock OS restore drill (FLO-288)"
echo "================================"
echo "  bench:        $BENCH_DIR"
echo "  source site:  $SOURCE_SITE"
echo "  drill site:   $DRILL_HOST"
echo

# --- 1. pre-backup source counts (the parity baseline) ------------------------
# Captured BEFORE the backup so a source that changes mid-run is still comparable
# to the point-in-time dump actually backed up.
echo "==> [1/4] capturing source row counts"
if ! capture_counts "$SOURCE_SITE" >"$TMP/source.tsv"; then
	echo "$PROG: failed to read source counts." >&2; exit 1
fi
n_dt="$(awk 'END{print NR}' "$TMP/source.tsv")"
n_rows="$(awk -F'\t' '{s+=$2} END{print s}' "$TMP/source.tsv")"
echo "    ${n_dt} Flock DocTypes, ${n_rows} total rows."

# --- 2. back the source site up -----------------------------------------------
echo "==> [2/4] backing up $SOURCE_SITE"
if ! "$SCRIPT_DIR/backup.sh" --bench-dir "$BENCH_DIR" --site "$SOURCE_SITE" --out "$TMP" >/tmp/flo288_backup.log 2>&1; then
	echo "$PROG: backup.sh failed:" >&2; tail -n 20 /tmp/flo288_backup.log >&2; exit 1
fi
ARCHIVE="$(grep -m1 '^  archive: ' /tmp/flo288_backup.log | sed 's/^  archive: //')"
[[ -n "$ARCHIVE" && -d "$ARCHIVE" ]] || { echo "$PROG: could not resolve archive path." >&2; exit 1; }
echo "    archive: $(basename "$ARCHIVE")"

# --- 3. restore into the drill site (created fresh or overwritten w/ --force) --
echo "==> [3/4] restoring into $DRILL_HOST"
RESTORE_ARGS=(--site "$DRILL_HOST" --confirm --force --bench-dir "$BENCH_DIR" --db-root-username "$DB_ROOT_USER" --db-root-password "$DB_ROOT_PW")
[[ -n "$ADMIN_PW" ]] && RESTORE_ARGS+=(--admin-password "$ADMIN_PW")
if ! "$SCRIPT_DIR/restore.sh" "$ARCHIVE" "${RESTORE_ARGS[@]}" >/tmp/flo288_restore.log 2>&1; then
	echo "$PROG: restore.sh failed:" >&2; tail -n 30 /tmp/flo288_restore.log >&2; exit 1
fi
echo "    restored."

# --- 4. parity check: restored counts must match the source baseline ----------
echo "==> [4/4] row-count parity check"
if ! capture_counts "$DRILL_HOST" >"$TMP/restored.tsv"; then
	echo "$PROG: failed to read restored counts." >&2; exit 1
fi
PYTHONPATH="$REPO_ROOT" python3 - "$TMP/source.tsv" "$TMP/restored.tsv" <<'PY'
import sys
from flock_os.utils.backup_drill import compare_counts, parse_counts

src = parse_counts(open(sys.argv[1]).read())
rst = parse_counts(open(sys.argv[2]).read())
ok, mismatches = compare_counts(src, rst)
print(f"    source doctypes: {len(src)}  restored doctypes: {len(rst)}")
if ok:
	print("PARITY: OK — restored site matches the source baseline across all Flock DocTypes.")
	sys.exit(0)
print("PARITY: FAIL — divergences:")
for m in mismatches:
	print(f"    - {m}")
sys.exit(1)
PY
status=$?
if [[ "$status" -ne 0 ]]; then
	echo "$PROG: parity check FAILED." >&2
	[[ "$KEEP" -eq 1 ]] || drop_site "$DRILL_HOST"
	exit "$status"
fi

# --- cleanup ------------------------------------------------------------------
if [[ "$KEEP" -eq 1 ]]; then
	echo
	echo "DRILL: PASS (drill site $DRILL_HOST kept; drop with: bench --site $DRILL_HOST drop-site --yes)"
else
	drop_site "$DRILL_HOST"
	echo
	echo "DRILL: PASS — backup restorable, row-count parity verified across all Flock DocTypes."
fi
exit 0
