_meta:
    env: ENC[AES256_GCM,data:4Z9O8g==,iv:FmzM5XDrk0MMpIR6SSWyEl4EAKzIGuG9yDzjsc+7kbg=,tag:SKx+FXSZDG9Z8FseiH9M3w==,type:str]
    description: ENC[AES256_GCM,data:oiKgkm9rAEcHMVGMiLD6hQ4uXBU3S6LXRWVkJw3ATMc7+sRy7wP5tqSVt/XeVAI80/IFnerSAyuRcZm71t4I,iv:/1HaRLa9sQosfBwThef4o8TXRBWmwHSup8LvZ1ZsgSQ=,tag:xmQCx4hol19Iw7QziiCxkQ==,type:str]
DB_HOST: ENC[AES256_GCM,data:JecYdsxa2TDB7MWNd035S6YCojGZj80HQw==,iv:vmExXqdhflH1riCRbKgBa3GFOjAsXWmr7R4CxTs31cc=,tag:MXQZmohPZQk2aRBOtDz5ZQ==,type:str]
DB_PORT: ENC[AES256_GCM,data:/kMGNA==,iv:a9IZdmovNq9sGhLDzomzImdvuuhSEk2li2Cq0j9U3Xw=,tag:uBDWtZRVb3khJZhWx7U6AA==,type:str]
DB_NAME: ENC[AES256_GCM,data:/h1N7py7KgCbeKsc/Q==,iv:0UjgP4HcNMMPEZmN3afiNHXC6OOSCpKx21JVmBeYTH4=,tag:HxSIYNkHwoKwnuRm12BMFA==,type:str]
DB_USER: ENC[AES256_GCM,data:wmL7IHYUjIguDRgFAA==,iv:sNcAucQkGs9obqLm8iIIecRZ3x/RNrUTV5gPZ3JHzHw=,tag:ZyMuyJZZMNLtV8bNMO0tSg==,type:str]
DB_PASSWORD: ENC[AES256_GCM,data:zKfs4z96df97HE2YpsIqk0rD/1QJl6z9F2uRb87ducZxgVM=,iv:GhuH+lLVTef2EInnw8et8KhvXLsVw6iscH0dv5ti5oQ=,tag:GP3ufMPpBjeIZsPqft0Wyw==,type:str]
REDIS_CACHE_URI: ENC[AES256_GCM,data:sAmjRTRtbTPxrYjIJ+QGXTWux7y3BA4jSP+/7NI6Qsa+Aj2l9HOE2/ioOQ==,iv:+T8V64aIpl/IU4V1TIAAXSji5RSrh/EQ5xxsavZRCH0=,tag:CQ71AetZre/27TIbT5osqA==,type:str]
REDIS_QUEUE_URI: ENC[AES256_GCM,data:yNHJcO3y5At5ouq9iqTz+Wy5ZWCO6HySINDgsPIl4F/kOSJTZzKmOTdJkA==,iv:4V81tcuTBni9fS7kDiYfFEDE//n0NYdOs6yBpKNeNGk=,tag:LXGkYZZEoa9cqL60RR+Clg==,type:str]
REDIS_SOCKETIO_URI: ENC[AES256_GCM,data:dzT8MiF3TRnyh2w1Bqi3PxaTyMxhmi2x5YHvsqG2n4ZQRSualUHJpQHcbAdKqg==,iv:o7iKdp5lkOWF7gahw7VkW2Olqrec6kELFfs7DuSvlj8=,tag:yojm0BRXYO/Zp2RlWMO0AQ==,type:str]
FLOCK_SIO_ADAPTER_REDIS: ENC[AES256_GCM,data:YlqZAGyorWs7gXB8RAh4MW8LsE4cjzAg3bZpk1rovWDvD//yUVcwXxWgGqhG,iv:97d/Gl4+XfEcr3HlJcj2oce6PB50VBnrRIJnYtZibHY=,tag:0xBa7AiYY1YUQ5YTcJXPNA==,type:str]
SECRET_KEY: ENC[AES256_GCM,data:iZArJlqyJ1Gxo2A76AhhXzKnjutWf1rAWLUTbp3P6jh07Q==,iv:i7CKC3pYIrwAepf9yf3iUleiAqAm8dJQVcHlcgdZosY=,tag:nmWZFXjeBNtlNeTMF1pMKg==,type:str]
SITE_URL: ENC[AES256_GCM,data:C9834sYH28oFyIZ6ExRmpj93yr0rq7Jl,iv:8xvhbM23cmKcL3hibQkiF8pTMrx2Jg++jvxLFxhv/Kg=,tag:XYZAa1RMSap9zO7YO6oEcg==,type:str]
FLOCK_ENV: ENC[AES256_GCM,data:vCS2lA==,iv:bH7qOQzKUcgNp3/3Ea5EB99Po2FA4cdKZ+bZkW3AbC0=,tag:zA1iSbMXW0JdlA0zKcbcQA==,type:str]
MUTE_EMAILS: ENC[AES256_GCM,data:4w==,iv:Wem3V19YwTH9aap4VqFi6t4VJyg36JURedYAlSvg2is=,tag:e443m/so5ZbcJB9GkEJS8g==,type:str]
FLOCK_SIO_PROCESSES: ENC[AES256_GCM,data:rw==,iv:c1jg0T0WpmKb0o3uEs5NWZ6VW54NLCB0OaFHJ8tLv08=,tag:FH3qoEhZ2d3pFbQ8pHP0pw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMmF0NGVrZEJJWUR6d2o2
            dzIrS0MrNTk3eWRGNWpudGZJdHNsVVVyRFFFCjI0dDdPaVBCS0VUQVVQNlc1REJp
            UmpFMk9zemVSMUtqanpISFJKRUkvTlUKLS0tIDFLeU8vcTVYZ0dwUVFHcDhCejFS
            bVN6NFBWMUtheDZFWU1KcmJJcDhIVU0KNo2HWTeY0ztckl5331ujK+1nY6JCEF7y
            r4lKBi2ozlQLMBFBRQqo+n2ci2X2GcGVC/ex1d16TcnnOFr59rkbyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w58g9v5u4w0lwnvyeffdjdmtzcdru4tfcjm8cyr0uva4hyn325zshjn76j
    lastmodified: "2026-06-20T00:19:45Z"
    mac: ENC[AES256_GCM,data:XtX51919rmOzp/4XNJTnITuVJ2TUPoxj9YIqDYEomKvKYKeC83Y5ogXDmQNhhxi09voE4uzvvILTJmaSknGKm7OCzj0K3N2QLuRLLngDLPH+sz3MmX3yOt3Kk5mXKn6GQOh4skGZypBcmDIfCAeMqyPYyiquNMUahOYClCEBmFw=,iv:/onMEPQpNb8Pdas5EH0DtFrrncNKmP6MTeS6TttsaMU=,tag:Gyem5aYZ0x+a53PfIKVmKQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
